### PR TITLE
described more about the repository Update README.md

### PR DESCRIPTION
**Pull request by Vardanbhaskar**

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@Vardanbhaskar I know it is Hacktoberfest and I am very grateful for contributions but that is not improving anything. Thus either please improve what you are trying to achieve or close the PR.

**Comment by Vardanbhaskar** [comment]
> @Vardanbhaskar I know it is Hacktoberfest and I am very grateful for contributions but that is not improving anything. Thus either please improve what you are trying to achieve or close the PR.

@SchoolGuy  it's nice to hear from your side. I understand your concern as well. Actually, I was just searching randomly about the programming competitions and Hacktoberfest popped out. I know Python basis but as it is my 1st e-programming competition so I am not having the experience. So I request you to check my request because "The smallest of contributions made collectively makes the biggest difference.”And I assure you that after gaining a full experience I will 1st work on your project and customize it according to your needs.
Looking Forward
Vardan Bhaskar

**Comment by SchoolGuy** [comment]
This specifc repository has nothing to do with Python. Although the main application is of course in Pyhton. Also the Hacktoberfest is not competion. It is thought as an encouragement to contribute to open source. Thus I will close your PR. If you have something of value to contribute I am more then happy to help!

**Comment by Vardanbhaskar** [comment]
> This specifc repository has nothing to do with Python. Although the main application is of course in Pyhton. Also the Hacktoberfest is not competion. It is thought as an encouragement to contribute to open source. Thus I will close your PR. If you have something of value to contribute I am more then happy to help!

@SchoolGuy  plz tell that what improvement can I bring to your project?.

**Pull request closed without merging**
