### PR TITLE
Update the gears image (impossible rotation) with a working one

### PR DESCRIPTION
**Pull request by xenlo**
Credits: Photo by [Bill Oxford](https://unsplash.com/@bill_oxford) on [Unsplash](https://unsplash.com/photos/-fGqsewtsJY)

### CODE REVIEW

**Comment by brejoc** [comment]
@xenlo Could you please also change the attribution here!? Thanks!
https://github.com/cobbler/cobbler.github.io/blob/master/_includes/footer.html#L71

**Comment by xenlo** [comment]
Credits updated in the footer.

**Comment by SchoolGuy** [comment]
@xenlo I will Rebase/Solve the conflict in the afternoon and then merge!

**Comment by SchoolGuy** [comment]
Github sadly did not detect my merge on the command line so sadly I have to close this... But your changes are inside master! :tada:

**Pull request closed without merging**
