### PR TITLE
WIP: New branding

### PR DESCRIPTION
**Pull request by SchoolGuy**
This PR should do the following:

- [x] Remove Travis Dependency
- [x] Remove the Quickstart and exchange the footer link
- [x] Add a page about the branding of Cobbler
- [x] Delete the out of date bootloaders
- [x] Remove self hosting of Bootstrap
- [x] Upgrade to Bootstrap Version 5
- [x] Fonteawesome Update

### CODE REVIEW

**Comment by hbokh** [comment]
Looks definitely better than it was!! 👍🏻

Reference: https://registry.terraform.io/namespaces/cobbler

**Comment by nodeg** [comment]
What I found so far

- [ ] `users.html`: Pictures have to be bigger and middle centered. Furthermore the slide show of them is not working. Why using a slide show at all and not use the old layout?
- [ ] `blog/2021/03/04/cobbler_3.2.1_released.html`: Remove the unserscores (`_`).
- [ ] `quickstart`: Is missing when clicking on `Get started now!` on the main page.
- [ ] `footer`: Move attribution into its own subpage.
- [ ]  `footer`: Social is empty. Maybe add Gitter as well here.

**Comment by SchoolGuy** [comment]
@nodeg Social was not empty... Twitter should be there, but I guess your Adblock/Scriptblocker did not like that button... 😄

**Comment by nodeg** [comment]
Good point. I should test in a private browser instance or without adblocking, indeed.

**Comment by SchoolGuy** [comment]
@nodeg Please re-review!

**Review by nodeg — APPROVED** [review]
LGTM. Thanks for the hard work and the improvements.

**Pull request merged**
