### PR TITLE
Add signature for Ubuntu 22.04 (jammy)

### PR DESCRIPTION
**Pull request by dansou901**
Hi,
as suggested in the chat, here is my pull request with the signature for jammy. Keep in mind that autoinstall won't work with this until cloud-init support is added to cobbler. Also, as soon as cloud-init support is there, this signature will need updating.
Regards,
dansou901

### CODE REVIEW

**Review by SchoolGuy — APPROVED** [review]
LGTM. If it is not too much trouble I would love having this in the other files as well.

**Comment by dansou901** [comment]
I won't make it today anymore and I'll be on vacation the next week. I'll have my laptop with me so maybe I can do it but I can't guarantee.

**Comment by SchoolGuy** [comment]
@dansou901 No hurry from my side. There is a lot to do before this is useful anyway sadly.

**Review by SchoolGuy — APPROVED** [review]
LGTM

**Pull request merged**
